alter session set "_ORACLE_SCRIPT"=true;  

drop user "DevDB_Stage" CASCADE; 

-- USER SQL
CREATE USER DevDB_Stage IDENTIFIED BY DevDB_Stage  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS

-- ROLES
GRANT CONNECT TO DevDB_Stage ;
GRANT RESOURCE TO DevDB_Stage ;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO DevDB_Stage ;
GRANT DROP ANY TRIGGER TO DevDB_Stage ;
GRANT ALTER ANY INDEX TO DevDB_Stage ;
GRANT DROP ANY SEQUENCE TO DevDB_Stage ;
GRANT CREATE ROLE TO DevDB_Stage ;
GRANT CREATE TRIGGER TO DevDB_Stage ;
GRANT CREATE ANY PROCEDURE TO DevDB_Stage ;
GRANT ALTER SESSION TO DevDB_Stage ;
GRANT CREATE ANY INDEX TO DevDB_Stage ;
GRANT GRANT ANY OBJECT PRIVILEGE TO DevDB_Stage ;
GRANT CREATE ANY SEQUENCE TO DevDB_Stage ;
GRANT CREATE VIEW TO DevDB_Stage ;
GRANT ALTER ANY TABLE TO DevDB_Stage ;
GRANT CREATE SESSION TO DevDB_Stage ;
GRANT BECOME USER TO DevDB_Stage ;
GRANT SELECT ANY TABLE TO DevDB_Stage ;
GRANT DELETE ANY TABLE TO DevDB_Stage ;
GRANT ALTER ANY SEQUENCE TO DevDB_Stage ;
GRANT DROP ANY RULE SET TO DevDB_Stage ;
GRANT CREATE TABLE TO DevDB_Stage ;
GRANT DROP ANY TABLE TO DevDB_Stage ;
GRANT SELECT ANY SEQUENCE TO DevDB_Stage ;
GRANT CREATE TYPE TO DevDB_Stage ;
GRANT CREATE TABLESPACE TO DevDB_Stage ;
GRANT SELECT ANY TRANSACTION TO DevDB_Stage ;
GRANT DROP ANY TYPE TO DevDB_Stage ;
GRANT DROP ANY RULE TO DevDB_Stage ;
GRANT CREATE ANY JOB TO DevDB_Stage ;
GRANT ALTER USER TO DevDB_Stage ;
GRANT CREATE ANY SYNONYM TO DevDB_Stage ;
GRANT EXECUTE ANY PROCEDURE TO DevDB_Stage ;
GRANT EXECUTE ANY PROGRAM TO DevDB_Stage ;
GRANT EXECUTE ANY TYPE TO DevDB_Stage ;
GRANT CREATE SEQUENCE TO DevDB_Stage ;
GRANT CREATE ANY INDEXTYPE TO DevDB_Stage ;
GRANT DROP ANY INDEX TO DevDB_Stage ;
GRANT CREATE USER TO DevDB_Stage ;
GRANT ALTER ANY ROLE TO DevDB_Stage ;
GRANT UPDATE ANY TABLE TO DevDB_Stage ;
GRANT DROP ANY VIEW TO DevDB_Stage ;
GRANT EXECUTE ANY RULE TO DevDB_Stage ;
GRANT GRANT ANY PRIVILEGE TO DevDB_Stage ;
GRANT ALTER ANY TRIGGER TO DevDB_Stage ;
GRANT CREATE ANY VIEW TO DevDB_Stage ;
GRANT READ ANY TABLE TO DevDB_Stage ;
GRANT DROP USER TO DevDB_Stage ;
GRANT INSERT ANY TABLE TO DevDB_Stage ;
GRANT ALTER ANY TYPE TO DevDB_Stage ;
GRANT DROP ANY PROCEDURE TO DevDB_Stage ;
GRANT DROP ANY INDEXTYPE TO DevDB_Stage ;
GRANT DROP ANY ROLE TO DevDB_Stage ;
GRANT CREATE ANY TRIGGER TO DevDB_Stage ;
GRANT CREATE ANY TABLE TO DevDB_Stage ;
GRANT CREATE ANY TYPE TO DevDB_Stage ;
GRANT CREATE PROCEDURE TO DevDB_Stage ;
GRANT ALTER DATABASE TO DevDB_Stage ;
GRANT GRANT ANY ROLE TO DevDB_Stage ;
GRANT ALTER ANY RULE TO DevDB_Stage ;

alter user DevDB_Stage quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO DevDB_Stage;