alter session set "_ORACLE_SCRIPT"=true;  

drop user "DevDB_Prod" CASCADE; 

-- USER SQL
CREATE USER DevDB_Prod IDENTIFIED BY DevDB_Prod  
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

-- QUOTAS

-- ROLES
GRANT CONNECT TO DevDB_Prod ;
GRANT RESOURCE TO DevDB_Prod ;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO DevDB_Prod ;
GRANT DROP ANY TRIGGER TO DevDB_Prod ;
GRANT ALTER ANY INDEX TO DevDB_Prod ;
GRANT DROP ANY SEQUENCE TO DevDB_Prod ;
GRANT CREATE ROLE TO DevDB_Prod ;
GRANT CREATE TRIGGER TO DevDB_Prod ;
GRANT CREATE ANY PROCEDURE TO DevDB_Prod ;
GRANT ALTER SESSION TO DevDB_Prod ;
GRANT CREATE ANY INDEX TO DevDB_Prod ;
GRANT GRANT ANY OBJECT PRIVILEGE TO DevDB_Prod ;
GRANT CREATE ANY SEQUENCE TO DevDB_Prod ;
GRANT CREATE VIEW TO DevDB_Prod ;
GRANT ALTER ANY TABLE TO DevDB_Prod ;
GRANT CREATE SESSION TO DevDB_Prod ;
GRANT BECOME USER TO DevDB_Prod ;
GRANT SELECT ANY TABLE TO DevDB_Prod ;
GRANT DELETE ANY TABLE TO DevDB_Prod ;
GRANT ALTER ANY SEQUENCE TO DevDB_Prod ;
GRANT DROP ANY RULE SET TO DevDB_Prod ;
GRANT CREATE TABLE TO DevDB_Prod ;
GRANT DROP ANY TABLE TO DevDB_Prod ;
GRANT SELECT ANY SEQUENCE TO DevDB_Prod ;
GRANT CREATE TYPE TO DevDB_Prod ;
GRANT CREATE TABLESPACE TO DevDB_Prod ;
GRANT SELECT ANY TRANSACTION TO DevDB_Prod ;
GRANT DROP ANY TYPE TO DevDB_Prod ;
GRANT DROP ANY RULE TO DevDB_Prod ;
GRANT CREATE ANY JOB TO DevDB_Prod ;
GRANT ALTER USER TO DevDB_Prod ;
GRANT CREATE ANY SYNONYM TO DevDB_Prod ;
GRANT EXECUTE ANY PROCEDURE TO DevDB_Prod ;
GRANT EXECUTE ANY PROGRAM TO DevDB_Prod ;
GRANT EXECUTE ANY TYPE TO DevDB_Prod ;
GRANT CREATE SEQUENCE TO DevDB_Prod ;
GRANT CREATE ANY INDEXTYPE TO DevDB_Prod ;
GRANT DROP ANY INDEX TO DevDB_Prod ;
GRANT CREATE USER TO DevDB_Prod ;
GRANT ALTER ANY ROLE TO DevDB_Prod ;
GRANT UPDATE ANY TABLE TO DevDB_Prod ;
GRANT DROP ANY VIEW TO DevDB_Prod ;
GRANT EXECUTE ANY RULE TO DevDB_Prod ;
GRANT GRANT ANY PRIVILEGE TO DevDB_Prod ;
GRANT ALTER ANY TRIGGER TO DevDB_Prod ;
GRANT CREATE ANY VIEW TO DevDB_Prod ;
GRANT READ ANY TABLE TO DevDB_Prod ;
GRANT DROP USER TO DevDB_Prod ;
GRANT INSERT ANY TABLE TO DevDB_Prod ;
GRANT ALTER ANY TYPE TO DevDB_Prod ;
GRANT DROP ANY PROCEDURE TO DevDB_Prod ;
GRANT DROP ANY INDEXTYPE TO DevDB_Prod ;
GRANT DROP ANY ROLE TO DevDB_Prod ;
GRANT CREATE ANY TRIGGER TO DevDB_Prod ;
GRANT CREATE ANY TABLE TO DevDB_Prod ;
GRANT CREATE ANY TYPE TO DevDB_Prod ;
GRANT CREATE PROCEDURE TO DevDB_Prod ;
GRANT ALTER DATABASE TO DevDB_Prod ;
GRANT GRANT ANY ROLE TO DevDB_Prod ;
GRANT ALTER ANY RULE TO DevDB_Prod ;

alter user DevDB_Prod quota unlimited on USERS;
GRANT UNLIMITED TABLESPACE TO DevDB_Prod;